// STATES
export const FETCH_STATES = 'FETCH_STATES';
export const CHANGE_STATE = 'CHANGE_STATE';

// RENT VALUE
export const CHANGE_RENT_VALUE = 'CHANGE_RENT_VALUE';

// BUY VALUE
export const CHANGE_BUY_VALUE = 'CHANGE_BUY_VALUE';

// LIVING TIME
export const CHANGE_LIVE_TIME_VALUE = 'CHANGE_LIVE_TIME_VALUE';

// ANNUAL TAX
export const CHANGE_ANNUAL_TAX_VALUE = 'CHANGE_ANNUAL_TAX_VALUE';

// TOTAL COST
export const FETCH_TOTAL_COST = 'FETCH_TOTAL_COST';